name: Build Tweak

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Build rootless
        run: |
          make package THEOS_PACKAGE_SCHEME=rootless

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: RedirectVoWiFiTweak
          path: packages/*.deb
